#!/bin/sh
exec tini -- chromium-browser \
--disable-background-networking \
--disable-breakpad \
--disable-default-apps \
--disable-extensions \
--disable-gpu \
--disable-sync \
--disable-translate \
--headless \
--incognito \
--metrics-recording-only \
--mute-audio \
--no-default-browser-check \
--no-first-run \
--no-sandbox \
--remote-debugging-address=0.0.0.0 \
--remote-debugging-port=9222 \
--safebrowsing-disable-auto-update \
--user-data-dir=/tmp \
--user-agent="${USER_AGENT}"
