version: "3.2"
services:
  rendering-proxy-chromium:
    build:
      context: ..
      dockerfile: ./docker/chromium.Dockerfile
    links:
      - "testserver"
    ports:
      - "8080:8080"

  rendering-proxy-firefox:
    build:
      context: ..
      dockerfile: ./docker/firefox.Dockerfile
    links:
      - "testserver"
    ports:
      - "8081:8080"

  testserver:
    image: kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b

  testcurl:
    image: byrnedo/alpine-curl:latest@sha256:fb9d2c02dbdf3d1872cdac0a5c8a293975ed6bffbe41e76aadbc03407cd86b2f
