version: "3.9"
services:
  rendering-proxy-chromium:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ['server', '--browser=chromium']
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:8080/health/"]
      interval: 1s
      timeout: 1s
      retries: 10

  rendering-proxy-firefox:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ['server', '--browser=firefox']
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:8080/heatlh/"]
      interval: 1s
      timeout: 1s
      retries: 10
