name: test with docker
on:
  - pull_request

concurrency:
  group: docker-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build docker image
        run: |
          docker compose -f docker/docker-compose.yml build

      - name: Test server mode
        run: |
          docker compose -f docker/docker-compose.yml up -d
          docker compose -f docker/docker-compose.yml ps -a
          sleep 5
          docker compose -f docker/docker-compose.yml ps -a
          docker compose -f docker/docker-compose.yml exec rendering-proxy-chromium bun run test
          docker compose -f docker/docker-compose.yml exec rendering-proxy-firefox bun run test
