name: gh-counter
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  gh-counter:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/gh-counter.yml@main
