name: Release

on:
  push:
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: install and build
        run: |
          yarn install
          yarn build

      - name: update version
        if: github.event_name == 'release'
        run: |
          git config user.email "dummy@dummy"
          git config user.name "dummy"
          npm version from-git --allow-same-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm pack

      - name: Test installation
        run: |
          set -eu
          built_dir=$(pwd)
          tempdir=$(mktemp -d)
          cd $tempdir
          yarn add $built_dir/*.tgz
          yarn run rendering-proxy --help
          cd $built_dir
          rm -rf $tempdir

      - run: npm publish
        if: github.event_name == 'release' && !github.event.release.prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
